travis:
  secure:
    BINSTAR_TOKEN: IouF6v+oafwuKP0m/mvKNvdtvmC6+q+jU4+BpQQO2qdg1AK/FfdMBismyf3C9pUlFnkz2O5T2f6FZDBLSDQXn2EkbMUaVRbdP34hOl3B/l9cQmzkwSGKHYjqfPzHdL40unWZb3BeqpG6QuZtLIZ2fRV5Yl7pn8z7oU24Zk0GzwuHsGOUgSbNH0Ch6NVjrLF4ByWb+b5kPvlR2RuvjOcuL6eW/QjPT6j82Rw1xqkPypcewVq4m4kWelLImV0BFMKthrE3wpR36C/gwdiRljS7ObAAFTSgL8E0rpUzSqtYIVNu1Hcli6C7wxuEX0FShi7di8TL7o22ph02qrGbsj42gBU4x0QieJgYBjTkbKze1RhPeLmS9MIUa2BWegAqXrNFv+1d8dRl4yiK+0xXqWH4rMgpSrNPjyK+PZ/51NhxfmSut5Wog1nim0GgOvvnTobonvPzm+o3sejfxFoGyOb0dVBE5J74I+4vJKUFWbQrYg2EM5ukJyc687o+RTu3tm26cZaVa/iNFANvCl2Pq6hGO0/c0hjtU1nw1r7CY+ORw+Mt5j5l0rSgG1j/f1ugxwp6EFsDyI4IBkj0JXviL5uSJHh1bvLmLG7EcIrbjat8Fr7QMzZ+dr7EnbucBI4XVxXJRyqzbSod3TE2jEcidOrfK4tThe1q9OnHXN+A+Rfrgk4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
